### ISSUE TITLE
Incorrect URL Assumption, Pitch Parameter Type Mismatch, and Missing Error Logs in MiniMax API Integration

### ISSUE THREAD

**Issue by zevcc-gh** [pipecat-ai/pipecat#2094]
### pipecat version

0.0.73

### Python version

3.12.8

### Operating System

macOS

### Issue description

There are two URLs for MiniMax, one for China and one for global use. However, the class implementation assumes the use of the China URL by default.

```
self._base_url = f"https://api.minimaxi.chat/v1/t2a_v2?GroupId={group_id}"
# Global version:
# https://api.minimax.io/v1/t2a_v2?GroupId=${group_id}
```

Additionally, there is an issue with the pitch parameter type in the InputParams class:
```
    class InputParams(BaseModel):
        """Configuration parameters for MiniMax TTS.

        Parameters:
            language: Language for TTS generation.
            speed: Speech speed (range: 0.5 to 2.0).
            volume: Speech volume (range: 0 to 10).
            pitch: Pitch adjustment (range: -12 to 12).
            emotion: Emotional tone (options: "happy", "sad", "angry", "fearful",
                "disgusted", "surprised", "neutral").
            english_normalization: Whether to apply English text normalization.
        """

        language: Optional[Language] = Language.EN
        speed: Optional[float] = 1.0
        volume: Optional[float] = 1.0
        pitch: Optional[float] = 0
        emotion: Optional[str] = None
        english_normalization: Optional[bool] = None
```

The pitch parameter type should be int instead of float.

Lastly, when providing invalid parameters, there is no error log to indicate the issue. Instead, the program becomes unresponsive.

### Reproduction steps

no

### Expected behavior

If an error occurs during the API call (e.g., invalid parameters), the program should log the error with a clear message.

### Actual behavior

No error logs are displayed, and the program becomes stuck.

### Logs

```shell

```
